---

- hosts: all
  remote_user: root
  tasks:
    - name: apt-key add
      apt_key:
        url: "{{ item.url }}"
        state: "{{ item.state }}"
      with_items:
        - { state: "present", url: "https://download.docker.com/linux/ubuntu/gpg" }

    - name: apt-add-repository
      apt_repository:
        repo: "{{ item.repo }}"
        state: "{{ item.state }}"
      with_items:
        - { state: "absent", repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu zesty stable" }
        - { state: "absent", repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu artful edge" }
        - { state: "absent", repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic test" }
        - { state: "present", repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic edge" }

    - name: apt install
      apt:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      with_items:
        - { state: "absent", name: "docker" }
        - { state: "absent", name: "docker-engine" }
        - { state: "absent", name: "docker.io" }
        - { state: "latest", name: "docker-ce" }

    - name: enable service
      service:
        name: "{{ item.name }}"
        enabled: "{{ item.enabled }}"
      with_items:
        - { name: "docker", enabled: "yes" }

    - name: pip install
      pip:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      with_items:
        - { state: "absent", name: "docker-compose" }
        - { state: "absent", name: "docker-py" }
        - { state: "latest", name: "docker" }
