---

- hosts: all
  remote_user: root
  tasks:
    - name: apt-get dist-upgrade
      apt:
        cache_valid_time: "3600"
        update_cache: "yes"
        upgrade: "dist"

    - name: apt install
      apt:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      with_items:
        - { state: "absent", name: "python-pip" }
        - { state: "absent", name: "cloud-init" }
        - { state: "latest", name: "apt-transport-https" }
        - { state: "latest", name: "aptitude" }
        - { state: "latest", name: "build-essential" }
        - { state: "latest", name: "ca-certificates" }
        - { state: "latest", name: "debian-archive-keyring" }
        - { state: "latest", name: "debian-keyring" }
        - { state: "latest", name: "dselect" }
        - { state: "latest", name: "linux-generic" }
        - { state: "latest", name: "python-dev" }
        - { state: "latest", name: "python-minimal" }
        - { state: "latest", name: "tasksel" }

    - name: dselect update
      shell: |
        DEBIAN_FRONTEND=noninteractive dselect update
      register: dselect_update_result
      changed_when: dselect_update_result.rc != 0

    - name: tasksel install
      shell: |
        DEBIAN_FRONTEND=noninteractive tasksel install {{ item.name }}
      with_items:
        - { name: "openssh-server" }
        - { name: "server" }
        - { name: "vanilla-gnome-desktop" }
      register: tasksel_update_result
      changed_when: tasksel_update_result.rc != 0

    - name: apt-add-repository
      apt_repository:
        repo: "{{ item.repo }}"
        state: "{{ item.state }}"
      with_items:
        - { state: "present", repo: "ppa:graphics-drivers/ppa" }
        - { state: "present", repo: "ppa:ubuntu-x-swat/updates" }

    - name: ubuntu-drivers autoinstall
      shell: |
        DEBIAN_FRONTEND=noninteractive ubuntu-drivers autoinstall
      register: ubuntu_drivers_autoinstall_result
      changed_when: ubuntu_drivers_autoinstall_result.rc != 0

    - name: fix NetworkManager
      shell: |
        rm -rf /usr/lib/NetworkManager/conf.d/10-globally-managed-devices.conf
        rm -rf /etc/netplan/*
      register: fix_networkmanager_result
      changed_when: fix_networkmanager_result.rc != 0

    - name: fix grub2
      shell: |
        cp /usr/share/grub/*.pf2 /boot/grub/
        sed -i 's/^\(GRUB_HIDDEN_TIMEOUT\)=\(.*\)$/#\1=\2/g' /etc/default/grub
        sed -i 's/^\(GRUB_HIDDEN_TIMEOUT_QUIET\)=\(.*\)$/#\1=\2/g' /etc/default/grub
        sed -i 's/^\(GRUB_TIMEOUT\)=\(.*\)$/\1=3/g' /etc/default/grub
        sed -i 's/^\(GRUB_CMDLINE_LINUX\)=\(.*\)$/\1="cgroup_enable=memory swapaccount=1"/g' /etc/default/grub
        update-grub
      register: fix_grub2_result
      changed_when: fix_grub2_result.rc != 0

    - name: fix resolv.conf
      file:
        src: "/run/systemd/resolve/resolv.conf"
        dest: "/etc/resolv.conf"
        state: "link"
        force: "yes"

    - name: fix Bluetooth Mouse M557
      lineinfile:
        path: "/usr/share/gnome-bluetooth/pin-code-database.xml"
        regexp: "^\t<device oui=\"00:1F:20:\".*$"
        line: "\t<device oui=\"00:1F:20:\" type=\"mouse\" name=\"Bluetooth Mouse M557\" pin=\"0000\" />"
        state: "present"
