---

- hosts: all
  remote_user: root
  tasks:
    - name: apt install
      apt:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      with_items:
        - { state: "latest", name: "bleachbit" }
        - { state: "latest", name: "blender" }
        - { state: "latest", name: "bmon" }
        - { state: "latest", name: "chrome-gnome-shell" }
        - { state: "latest", name: "colordiff" }
        - { state: "latest", name: "dia" }
        - { state: "latest", name: "dia-shapes" }
        - { state: "latest", name: "dos2unix" }
        - { state: "latest", name: "doxygen" }
        - { state: "latest", name: "duplicity" }
        - { state: "latest", name: "filezilla" }
        - { state: "latest", name: "flashplugin-installer" }
        - { state: "latest", name: "fonts-arphic-ukai" }
        - { state: "latest", name: "fonts-arphic-uming" }
        - { state: "latest", name: "fonts-nanum-coding" }
        - { state: "latest", name: "fonts-noto" }
        - { state: "latest", name: "fonts-noto-cjk" }
        - { state: "latest", name: "fonts-noto-cjk-extra" }
        - { state: "latest", name: "fonts-noto-hinted" }
        - { state: "latest", name: "fonts-noto-mono" }
        - { state: "latest", name: "fonts-noto-unhinted" }
        - { state: "latest", name: "fonts-takao-gothic" }
        - { state: "latest", name: "fonts-takao-mincho" }
        - { state: "latest", name: "fonts-unfonts-core" }
        - { state: "latest", name: "gir1.2-atk-1.0" }
        - { state: "latest", name: "gir1.2-clutter-1.0" }
        - { state: "latest", name: "gir1.2-gdkpixbuf-2.0" }
        - { state: "latest", name: "gir1.2-glib-2.0" }
        - { state: "latest", name: "gir1.2-gmenu-3.0" }
        - { state: "latest", name: "gir1.2-gtk-3.0" }
        - { state: "latest", name: "gir1.2-gtop-2.0" }
        - { state: "latest", name: "gir1.2-mutter-3" }
        - { state: "latest", name: "gir1.2-pango-1.0" }
        - { state: "latest", name: "gnome-system-tools" }
        - { state: "latest", name: "gnome-tweak-tool" }
        - { state: "latest", name: "gnucash" }
        - { state: "latest", name: "gufw" }
        - { state: "latest", name: "handbrake" }
        - { state: "latest", name: "htop" }
        - { state: "latest", name: "ibus" }
        - { state: "latest", name: "ibus-chewing" }
        - { state: "latest", name: "ibus-hangul" }
        - { state: "latest", name: "ibus-mozc" }
        - { state: "latest", name: "ibus-sunpinyin" }
        - { state: "latest", name: "ibus-table" }
        - { state: "latest", name: "ibus-table-cangjie3" }
        - { state: "latest", name: "ibus-table-cangjie5" }
        - { state: "latest", name: "ibus-table-quick-classic" }
        - { state: "latest", name: "ibus-table-quick5" }
        - { state: "latest", name: "ibus-table-wubi" }
        - { state: "latest", name: "ideviceinstaller" }
        - { state: "latest", name: "libimobiledevice-utils" }
        - { state: "latest", name: "libimobiledevice6" }
        - { state: "latest", name: "lsb" }
        - { state: "latest", name: "mcrypt" }
        - { state: "latest", name: "network-manager-openvpn-gnome" }
        - { state: "latest", name: "nmap" }
        - { state: "latest", name: "nmon" }
        - { state: "latest", name: "openshot" }
        - { state: "latest", name: "openvpn" }
        - { state: "latest", name: "p7zip" }
        - { state: "latest", name: "p7zip-full" }
        - { state: "latest", name: "pandoc" }
        - { state: "latest", name: "playonlinux" }
        - { state: "latest", name: "pwgen" }
        - { state: "latest", name: "python-gi" }
        - { state: "latest", name: "remmina" }
        - { state: "latest", name: "smartmontools" }
        - { state: "latest", name: "sqlite3" }
        - { state: "latest", name: "sshfs" }
        - { state: "latest", name: "tlp" }
        - { state: "latest", name: "tree" }
        - { state: "latest", name: "ubuntu-restricted-addons" }
        - { state: "latest", name: "ubuntu-restricted-extras" }
        - { state: "latest", name: "unrar" }
        - { state: "latest", name: "vlc" }
