---

- hosts: all
  remote_user: root
  tasks:
    - name: apt-key add
      apt_key:
        keyserver: "{{ item.keyserver }}"
        id: "{{ item.id }}"
        state: "{{ item.state }}"
      with_items:
        - { state: "present", keyserver: "pgp.mit.edu", id: "AD319E0F7CFFA38B4D9F6E55CE3F3DE92099F7A4" }

    - name: apt-add-repository
      apt_repository:
        repo: "{{ item.repo }}"
        state: "{{ item.state }}"
      with_items:
        - { state: "present", repo: "deb https://vagrant-deb.linestarve.com/ any main" }

    - name: apt install
      apt:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      with_items:
        - { state: "latest", name: "vagrant" }
